project:
  type: website

metadata-files:
  - reference/_sidebar.yml

format:
  html:
    css:
      - reference/_styles-quartodoc.css

website:
  title: "PyLahman"
  page-navigation: true
  navbar:
    search: true
    right:
      - text: "API"
        href: reference/index.qmd
  sidebar:
    - id: reference
      contents: "_sidebar.yml"

quartodoc:
  package: pylahman
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    display_name: relative
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  title: "API Reference"

  sections:
    - title: Player Identification
      desc: Functions to lookup player identifiers or names.
      contents:
        - get_player_names
        - get_player_ids
    - title: Data Loading
      desc: Functions to load tables from the Lahman database.
      contents:
        - AllstarFull
        - Appearances
        - AwardsManagers
        - AwardsPlayers
        - AwardsShareManagers
        - AwardsSharePlayers
        - Batting
        - BattingPost
        - CollegePlaying
        - Fielding
        - FieldingOF
        - FieldingOFsplit
        - fielding_post
        - HallOfFame
        - HomeGames
        - Managers
        - ManagersHalf
        - Parks
        - People
        - Pitching
        - PitchingPost
        - Salaries
        - Schools
        - SeriesPost
        - Teams
        - TeamsFranchises
        - TeamsHalf
