# PyLahman

`pylahman` is a Python package for accessing the [**Lahman** Baseball Database](https://sabr.org/lahman-database/) via `pandas`.

> The **data** used in this package is provided by [SABR](https://sabr.org/) and is licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/).
> The data was last updated based on the source data available from <https://sabr.org/lahman-database/> on 2026-01-08.
>
> The surrounding **software** is licensed under the [MIT License](https://opensource.org/licenses/MIT).

## Installation

The `pylahman` package is available on [PyPI](https://pypi.org/project/pylahman/) and can be installed via `pip`.

```bash
pip install pylahman
```

## Documentation and Usage

Each table in the Lahman Baseball Database has a corresponding data loading function in `pylahman` with the same name.
For example, the `Pitching` table is accessed via the `Pitching()` function.
Descriptions of each data table can be found in the documentation for the corresponding data loading function in the [API Reference](reference/).

```{python}
import pylahman

Pitching = pylahman.Pitching()
print(Pitching.head())
```
